version: "3.9"

services:
  twitch_db:
    container_name: twitch_db
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db

  init_twitch_db:
    build:
      context: ./Init_DB
      dockerfile: Dockerfile
    container_name: init_twitch_db
    image: cesagram/m4d/init:1.1
    depends_on:
      - twitch_db
    environment:
      - MONGO_DB=mongodb://twitch_db:27017
      - MONGO_DB_NAME=games
      - MONGO_COLLECTION_NAME=games_collection

  twitch_api:
    build:
      context: ./Twitch_API
      dockerfile: Dockerfile
    image: cesagram/m4d/twitch_api:2.0
    ports:
      - 3000:3000
    container_name: twitch_api
    depends_on:
      init_twitch_db:
        condition: service_completed_successfully
    environment:
      - MONGO_DB=mongodb://twitch_db:27017/
      # - NEO4J_URL=http:///160.40.53.99:4567
      # - LANG_DETECT_URL=http:///160.40.53.99:12020/detect
      - LANG_DETECT_URL=http://lang-detector:12020/detect
      - NEO4J_URL=http://neo4j-api:4567
    #restart: unless-stopped

  twitch_ctrl:
    build:
      context: ./Twitch_Ctrl
      dockerfile: Dockerfile
    image: cesagram/m4d/twitch_ctrl:2.0
    container_name: twitch_ctrl
    depends_on:
      - twitch_api
    environment:
      - SOCKET_URL=http://twitch_api:3000
      # - BOOTSTRAP_SERVERS=160.40.53.99:9092
      # - NEO4J_URL=http://160.40.53.99:4567
      - BOOTSTRAP_SERVERS=kafka:9093
      - NEO4J_URL=http://neo4j-api:4567

volumes:
  mongo-data:    

networks:
  default:
    name: cesagram_network
    external: true