version: '3.9'
services:
  twitch_db:
    image: mongo:6.0
    ports:
        - "27018:27017"
    container_name: twitch_db
    volumes: 
        - ./mongo/data:/data/db
    restart: unless-stopped

  init_twitch_db:
    build:
      context: ./Init_DB
      dockerfile: Dockerfile
    container_name: init_twitch_db
    image: certh/m4d/init:1.0
    depends_on:
      - twitch_db
    environment:
      - MONGO_DB=mongodb://twitch_db:27017/

  twitch_api:
    build:
      context: ./Twitch_API
      dockerfile: Dockerfile
    image: certh/m4d/api:3.2
    ports:
      - 3000:3000
    container_name: twitch_api
    depends_on:
      init_twitch_db:
        condition: service_completed_successfully
    environment:
      - MONGO_DB=mongodb://twitch_db:27017/
    #restart: unless-stopped

  twitch_ctrl:
    build:
      context: ./Twitch_Ctrl
      dockerfile: Dockerfile
    image: certh/m4d/ctrl:2.2
    container_name: twitch_ctrl
    depends_on:
      - twitch_api
    environment:
      - SOCKET_URL=http://twitch_api:3000
    
